import type { EmailState } from "@/types/email";

export const navbackTemplate: EmailState = {
  subject: "🚀 AI Product Roadmap – Your AI Journey on BetterPlace LMS",
  recipients: "",
  template: "ai-roadmap-navback",
  blocks: [
    {
      id: "nb-topbar",
      type: "topbar",
      content: "skillBetter × Navback",
      meta: JSON.stringify({
        brandName: "skillBetter",
        byline: "by BetterPlace",
        partnerName: "Navback",
        partnerSub: "",
        label: "AI Product Roadmap",
      }),
    },
    {
      id: "nb-hero",
      type: "hero",
      content: "",
      meta: JSON.stringify({
        pill: "AI PRODUCT ROADMAP",
        pillEmoji: "🚀",
        title: "Your AI Journey on",
        titleHighlight: "BetterPlace LMS",
        body: "Dear Navback Team,\n\nWe're excited to share the next phase of AI innovation for Navback:",
        pointers: [
          { text: "Scheduler — Automated Communications & Engagement", subItems: [] },
          { text: "Reels-Style Learning Feed — Bite-sized learning", subItems: [] },
          { text: "AI-Driven Skill Assessments & AI-Powered Workflow Simulations", subItems: [] },
        ],
      }),
    },
    {
      id: "nb-hero-closing",
      type: "text",
      content: "",
      meta: JSON.stringify({
        eyebrow: "",
        eyebrowEmoji: "",
        title: "",
        body: "Looking forward to your thoughts as we continue building this journey together! 😇",
      }),
    },
    { id: "nb-divider-0", type: "divider", content: "" },
    {
      id: "nb-coming-next-intro",
      type: "text",
      content: "",
      meta: JSON.stringify({
        eyebrow: "COMING NEXT",
        eyebrowEmoji: "🔜",
        title: "Powerful Features in the Pipeline",
        body: "",
      }),
    },
    {
      id: "nb-scheduler-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "teal",
        label: "COMING SOON",
        labelEmoji: "📅",
        title: "Scheduler",
        subtitle: "Automated Communications & Engagement",
        bullets: [
          { title: "Scheduled learning nudges", text: "timely reminders to operations teams before reporting cycles, compliance deadlines, or system updates", check: "teal" },
          { title: "Recurring module distribution", text: "auto-assign courses, assessments & surveys at defined intervals (weekly/monthly/quarterly)", check: "teal" },
          { title: "Completion reminders", text: "automated follow-ups to ensure mandatory training is completed on time", check: "teal" },
          { title: "Configurable controls", text: "admins define frequency, start date, learner groups & number of occurrences", check: "teal" },
          { title: "Example", text: "Fund accounting teams automatically receive quarterly refresher modules on NAV calculation checks and reconciliation controls, ensuring all analysts stay aligned with internal audit and compliance requirements", check: "teal" },
        ],
      }),
    },
    {
      id: "nb-reels-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "navy",
        label: "COMING SOON",
        labelEmoji: "🎞️",
        title: "Reels-Style Learning Feed",
        subtitle: "Bite-sized learning for busy operations teams",
        bullets: [
          { title: "Short explainer videos", text: "quick walkthroughs on fund accounting workflows, reconciliation steps, and regulatory updates", check: "navy" },
          { title: "Process refreshers", text: "swipeable micro-learning that helps teams revisit complex concepts quickly", check: "navy" },
          { title: "Higher engagement", text: "fast, visual format improves retention vs traditional long modules", check: "navy" },
          { title: "Example", text: "An operations analyst swipes through a 45-second reel explaining reconciliation breaks, followed by a quick card summarizing how to identify and resolve mismatches during NAV reporting — all between daily processing tasks", check: "navy" },
        ],
      }),
    },
    { id: "nb-divider-1", type: "divider", content: "" },
    {
      id: "nb-may-release-intro",
      type: "text",
      content: "",
      meta: JSON.stringify({
        eyebrow: "PLANNED: MAY RELEASE",
        eyebrowEmoji: "🗓",
        eyebrowPill: true,
        title: "AI Capabilities Built for Operations Teams",
        body: "Two high-impact AI capabilities launching inside the chatbot — purpose-built for Navback's roles and training needs.",
      }),
    },
    {
      id: "nb-ai-assessment-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "purple",
        label: "AI POWERED",
        labelEmoji: "🧠",
        title: "AI-Driven Skill Assessments",
        subtitle: "Scenario-based capability evaluation",
        bullets: [
          { title: "Conversational assessments", text: "evaluate operational decision-making through real workflow scenarios instead of static quizzes", check: "purple" },
          { title: "Structured skill scorecards", text: "automatically generated reports highlighting learner strengths and knowledge gaps", check: "purple" },
          { title: "Role-specific evaluations", text: "assessments tailored for fund accounting, reconciliation, compliance & operations teams", check: "purple" },
          { title: "Standardized scoring", text: "competency mapping and pass thresholds built directly into the LMS engine", check: "purple" },
          { title: "Example", text: "A reconciliation analyst completes an AI-driven assessment simulating a break in trade vs cash reconciliation, receiving a scorecard highlighting improvement areas in exception handling and escalation protocols", check: "purple" },
        ],
      }),
    },
    {
      id: "nb-ai-simulation-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "navy",
        label: "AI POWERED",
        labelEmoji: "🎯",
        title: "AI-Powered Workflow Simulations",
        subtitle: "Practice real operational scenarios",
        bullets: [
          { title: "Interactive roleplay simulations", text: "practice resolving real fund operations scenarios before handling live cases", check: "teal" },
          { title: "Scenario-based learning", text: "covers NAV calculation checks, reconciliation breaks, corporate actions & reporting errors", check: "teal" },
          { title: "Instant AI feedback & coaching", text: "identifies decision gaps and recommends best practices", check: "teal" },
          { title: "Builds operational confidence", text: "analysts learn how to resolve issues before they impact reporting cycles", check: "teal" },
          { title: "Example", text: "An analyst practices resolving a mismatch during NAV computation caused by incorrect corporate action processing. The AI simulation evaluates the steps taken — verifying source data, checking ledger entries, and escalating the issue appropriately", check: "teal" },
        ],
      }),
    },
    {
      id: "nb-footer",
      type: "footer",
      content: "",
      meta: JSON.stringify({
        brandName: "skillBetter",
        byline: "by BetterPlace",
        tagline: "Thank you for being part of our journey. We're excited to continue building and growing together.",
        note: "You are receiving this as a valued partner.",
      }),
    },
  ],
};
