import type { EmailState } from "@/types/email";

export const purplleTemplate: EmailState = {
  subject: "🚀 AI Product Roadmap – Your AI Journey on BetterPlace LMS",
  recipients: "",
  template: "ai-roadmap-purplle",
  blocks: [
    {
      id: "pp-topbar",
      type: "topbar",
      content: "skillBetter × Purplle",
      meta: JSON.stringify({
        brandName: "skillBetter",
        byline: "by BetterPlace",
        partnerName: "Purplle",
        partnerSub: "",
        label: "AI Product Roadmap",
      }),
    },
    {
      id: "pp-hero",
      type: "hero",
      content: "",
      meta: JSON.stringify({
        pill: "AI PRODUCT ROADMAP",
        pillEmoji: "🚀",
        title: "Your AI Journey on",
        titleHighlight: "BetterPlace LMS",
        body: "Dear Purplle Team,\n\nWe're excited to share the next phase of AI innovation for Purplle:",
        pointers: [
          { text: "Scheduler — Automated Communications & Engagement", subItems: [] },
          { text: "Reels-Style Learning Feed — Bite-sized learning", subItems: [] },
          { text: "AI-Driven Skill Assessments & AI-Powered Sales Simulations", subItems: [] },
        ],
      }),
    },
    {
      id: "pp-hero-closing",
      type: "text",
      content: "",
      meta: JSON.stringify({
        eyebrow: "",
        eyebrowEmoji: "",
        title: "",
        body: "Looking forward to your thoughts as we continue building this journey together! 😇",
      }),
    },
    { id: "pp-divider-0", type: "divider", content: "" },
    {
      id: "pp-coming-next-intro",
      type: "text",
      content: "",
      meta: JSON.stringify({
        eyebrow: "COMING NEXT",
        eyebrowEmoji: "🔜",
        title: "Powerful Features in the Pipeline",
        body: "",
      }),
    },
    {
      id: "pp-scheduler-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "teal",
        label: "COMING SOON",
        labelEmoji: "📅",
        title: "Scheduler",
        subtitle: "Automated Communications & Engagement",
        bullets: [
          { title: "Scheduled learning nudges", text: "timely reminders to beauty advisors before new product launches, store campaigns, or training deadlines", check: "teal" },
          { title: "Recurring module distribution", text: "automatically assign courses, product training & quizzes at defined intervals (weekly/monthly)", check: "teal" },
          { title: "Completion reminders", text: "automated follow-ups ensure store staff complete mandatory training", check: "teal" },
          { title: "Configurable controls", text: "admins set frequency, start dates, learner groups & campaign timelines", check: "teal" },
          { title: "Example", text: "When a new skincare range launches, all beauty advisors automatically receive a product training module and short assessment, ensuring they are ready to confidently recommend the products to customers", check: "teal" },
        ],
      }),
    },
    {
      id: "pp-reels-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "navy",
        label: "COMING SOON",
        labelEmoji: "🎞️",
        title: "Reels-Style Learning Feed",
        subtitle: "Bite-sized learning for busy store teams",
        bullets: [
          { title: "Short beauty tutorials", text: "quick clips explaining product benefits, application techniques & selling tips", check: "navy" },
          { title: "Swipeable learning cards", text: "easy micro-learning format ideal for store associates", check: "navy" },
          { title: "Higher engagement", text: "visual, snackable content that staff can consume between customer interactions", check: "navy" },
          { title: "Example", text: "A beauty advisor watches a 45-second reel explaining the difference between matte and dewy foundations, followed by a quick card highlighting how to recommend the right finish based on skin type", check: "navy" },
        ],
      }),
    },
    { id: "pp-divider-1", type: "divider", content: "" },
    {
      id: "pp-may-release-intro",
      type: "text",
      content: "",
      meta: JSON.stringify({
        eyebrow: "PLANNED: MAY RELEASE",
        eyebrowEmoji: "🗓",
        eyebrowPill: true,
        title: "AI Capabilities Built for Retail Teams",
        body: "Two high-impact AI capabilities launching inside the chatbot — purpose-built for Purplle's roles and training needs.",
      }),
    },
    {
      id: "pp-ai-assessment-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "purple",
        label: "AI POWERED",
        labelEmoji: "🧠",
        title: "AI-Driven Skill Assessments",
        subtitle: "Evaluate real retail scenarios",
        bullets: [
          { title: "Conversational assessments", text: "test how beauty advisors respond to real customer queries", check: "purple" },
          { title: "Structured skill scorecards", text: "automatically generated reports showing product knowledge & consultation skills", check: "purple" },
          { title: "Role-specific evaluation", text: "covers skincare consultation, makeup recommendation, customer service & upselling", check: "purple" },
          { title: "Standardized scoring", text: "consistent evaluation across stores and locations", check: "purple" },
          { title: "Example", text: "A beauty advisor completes an AI-driven assessment simulating a customer asking for a skincare routine for acne-prone skin, receiving feedback on product recommendations and consultation approach", check: "purple" },
        ],
      }),
    },
    {
      id: "pp-ai-simulation-card",
      type: "ai-card",
      content: "",
      meta: JSON.stringify({
        variant: "navy",
        label: "AI POWERED",
        labelEmoji: "🎯",
        title: "AI-Powered Sales Simulations",
        subtitle: "Practice real customer conversations",
        bullets: [
          { title: "Interactive roleplay simulations", text: "practice customer interactions before handling them on the shop floor", check: "teal" },
          { title: "Scenario-based training", text: "covers product recommendations, cross-selling, and handling objections", check: "teal" },
          { title: "Instant AI coaching", text: "provides feedback on communication, product explanation & sales technique", check: "teal" },
          { title: "Builds real retail confidence", text: "associates approach customers with better product knowledge and confidence", check: "teal" },
          { title: "Example", text: "A beauty advisor practices a simulation where a customer is unsure whether to buy a serum or moisturizer. The AI evaluates how well the advisor explains benefits, asks skin-type questions, and recommends the right product", check: "teal" },
        ],
      }),
    },
    {
      id: "pp-footer",
      type: "footer",
      content: "",
      meta: JSON.stringify({
        brandName: "skillBetter",
        byline: "by BetterPlace",
        tagline: "Thank you for being part of our journey. We're excited to continue building and growing together.",
        note: "You are receiving this as a valued partner.",
      }),
    },
  ],
};
